In [476]:
import numpy as np
import math

In [506]:

# Give your input for x and y values
# For better testing I have taken the inputs(x and y values), total number of iterations, alpha value from coursera machine learning course. 



x = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y = np.array([460, 232, 178])

m = len(y)
n = len(x[0])

# initializing weights and bias as 0

w = np.zeros(x.shape[1])
b = 0

# Total numbers of iterations to perform

iteration = 1000

# Learning rate alpha

alpha = 5.0e-7

[2104    5    1   45]


In [449]:
# Our  linear Regression Model

def model(x,w,b):
    return np.dot(x,np.transpose(w))+b

In [450]:
def cost_function():
    cost=0
    for idx in range(m):
        cost += (model(x[idx],w,b) - y[idx])**2


    return cost/(2*m)
    

In [451]:
def update_b(w,b):
    value = 0 
    for i in range(m):
            value += (model(x[i],w,b) - y[i])

    return value

In [507]:
def gradient_decent():
    global b
    global w

    for i in range(iteration):
        tempw = w
   
  
        for j in range(n):

            derivative_val_w = 0 

            for k in range(m):
           
           
            
              derivative_val_w += (model(x[k],tempw,b) - y[k])*x[k][j]

            w[j] = w[j] - alpha*(derivative_val_w/m)
            
        
        tempb = b 
        b = tempb - alpha *((update_b(tempw,tempb))/m)
        if i% math.ceil(iteration / 10) == 0:
        
          print(f" iterations:  " +str(i) + f" cost : {cost_function():0.2f}")
      
        

In [508]:
gradient_decent()

 iterations:  0 cost : 2511.04
 iterations:  100 cost : 695.11
 iterations:  200 cost : 694.05
 iterations:  300 cost : 693.00
 iterations:  400 cost : 691.95
 iterations:  500 cost : 690.92
 iterations:  600 cost : 689.89
 iterations:  700 cost : 688.87
 iterations:  800 cost : 687.87
 iterations:  900 cost : 686.87


In [ ]:
# Coursera's results 


Iteration    0: Cost  2529.46   
Iteration  100: Cost   695.99   
Iteration  200: Cost   694.92   
Iteration  300: Cost   693.86   
Iteration  400: Cost   692.81   
Iteration  500: Cost   691.77   
Iteration  600: Cost   690.73   
Iteration  700: Cost   689.71   
Iteration  800: Cost   688.70   
Iteration  900: Cost   687.69

# Our Results 
 iterations:  0 cost : 2511.04
 iterations:  100 cost : 695.11
 iterations:  200 cost : 694.05
 iterations:  300 cost : 693.00
 iterations:  400 cost : 691.95
 iterations:  500 cost : 690.92
 iterations:  600 cost : 689.89
 iterations:  700 cost : 688.87
 iterations:  800 cost : 687.87
 iterations:  900 cost : 686.87



In [ ]:
# Testing it against Sklearns Linear Regression Model

In [510]:
from sklearn.linear_model import LinearRegression 
reg = LinearRegression().fit(x, y)
print(reg.coef_)
print(w)

[  0.39133535  18.75376741 -53.36032453 -26.42131618]
[ 0.20411633  0.00318732 -0.01143196 -0.07175368]


In [511]:
print(model(x[2],w,b))
print(y[2])
print(reg.predict([x[2]]))

171.38830506222902
178
[178.]


In [500]:
print(b,w)

-0.0023755406273586505 [ 0.20411809  0.00319058 -0.01144328 -0.07182288]
